### ISSUE TITLE
nextbike calls async_add_job, which is deprecated and will be removed in Home Assistant 2025.4

### ISSUE THREAD

**Issue by paszczaq** [syssi/nextbike#10]
Hi,

Looking at logs, I've noticed warning coming from nextbike integration that warns about upcoming changes in HA.

``Detected that custom integration 'nextbike' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/nextbike/sensor.py, line 149: hass.async_add_job(city.async_refresh), please create a bug report at https://github.com/syssi/nextbike/issues``

Any option to get it fixed before it will get deprecated?

**Comment by syssi** [comment]
I've pushed a fix and prepared a new release. Please give it a try!

**Comment by paszczaq** [comment]
Hi, thanks for quick fix  - I did upgrade but seems that something is not quite good.
After HA restart there are some errors about addon startup
```
Rejestrator: py.warnings
Źródło: runner.py:189
Pierwsze zdarzenie: 11:22:41 (1 zdarzenia)
Ostatnio zalogowany: 11:22:41

/usr/local/lib/python3.12/asyncio/base_events.py:1991: RuntimeWarning: coroutine 'NextbikeCity.async_refresh' was never awaited handle = None # Needed to break cycles when an exception occurs.
```

```
Rejestrator: homeassistant.components.sensor
Źródło: runner.py:189
integracja: Sensor (dokumentacja, Problemy)
Pierwsze zdarzenie: 11:22:51 (1 zdarzenia)
Ostatnio zalogowany: 11:22:51

Setup of sensor platform nextbike is taking over 10 seconds.
```


```
Rejestrator: homeassistant.components.sensor
Źródło: helpers/entity_platform.py:405
integracja: Sensor (dokumentacja, Problemy)
Pierwsze zdarzenie: 11:23:41 (1 zdarzenia)
Ostatnio zalogowany: 11:23:41

Setup of platform nextbike is taking longer than 60 seconds. Startup will proceed without waiting any longer.
```

**Comment by syssi** [comment]
Ouch. I will have a look!

**Comment by syssi** [comment]
I've prepared a bugfix release. Could you give it another try?

**Comment by paszczaq** [comment]
Thanks for such quick response, but unfortunetly its still problem with loading integration.

![Zrzut ekranu 2024-10-25 230223](https://github.com/user-attachments/assets/487fcae7-6281-40f4-9786-cb5a99f522dc)


```
Rejestrator: homeassistant.components.sensor
Źródło: runner.py:189
integracja: Sensor (dokumentacja, Problemy)
Pierwsze zdarzenie: 23:02:11 (1 zdarzenia)
Ostatnio zalogowany: 23:02:11

Setup of sensor platform nextbike is taking over 10 seconds.
```

I did full reinstall of 1.2.1 in HACS

Here's my sensor.yaml snippet:

```
- platform: nextbike
  name: Veturilo
  city_id: 812
  radius: 500
```

I will try to test on second instalnce of HA and let you know

**Comment by syssi** [comment]
I've changed the component initialization to speed things up. It should be good to go now. Please update to release `1.2.2`.

**Comment by paszczaq** [comment]
Works like a charm! Thanks!
