### ISSUE TITLE
Wrong city ID - problem with proper bike count

### ISSUE THREAD

**Issue by paszczaq** [syssi/nextbike#6]
Hi,
It seems that City ID have changed for Warszawa (in docs its showing 
```
VETURILO Poland
690 Warszawa-testy (52.2362, 21.0107)

```

but after putting proper config in my sensor.yaml
```
- platform: nextbike
  name: Warszawa
  city_id: 690
  latitude: 52.229435
  longitude: 21.094524
  radius: 1000
```

It throws error
```
`2023-03-08 08:56:24.317 ERROR (MainThread) [custom_components.nextbike.sensor] Could not connect to Nextbike API endpoint: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://maps.nextbike.net/maps/nextbike-live.json?&city=690')
2023-03-08 09:01:24.277 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):`
```

I've check https://maps.nextbike.net/maps/nextbike-live.json and it seems that Warszawa ID is 812, but when I use it it show 0 bikes in Home Assistant

**Comment by syssi** [comment]
I cannot reproduce the issue. If I add this sensor to my Home Assistant setup:

```
sensor:
  - platform: nextbike
    name: Warszawa
    city_id: 812
    latitude: 52.229435
    longitude: 21.094524
    radius: 1000
```

It looks like there a 5 bikes available in a radius of 1km at the moment:

![nextbike-warszawa](https://user-images.githubusercontent.com/2735933/223725587-5c0c8a56-5924-4e4f-82d5-7e707e52498a.png)

**Comment by syssi** [comment]
I've updated the list of city ids to avoid confusion in future! Thanks for your feedback!

**Comment by paszczaq** [comment]
@syssi - thanks! Ok, I just checked without latitude / longitude and it worked just fine :)
```
- platform: nextbike
  name: Veturilo
  city_id: 812
#   latitude: 52.229435
#   longitude: 21.094524
  radius: 1000
```

![image](https://user-images.githubusercontent.com/2835696/223736979-d95a2fef-0b61-485b-837b-a1b262819c30.png)

We can close this issue!
