### ISSUE TITLE
Nextbike sensor doesnt work after HASS update to 2023.11.0

### ISSUE THREAD

**Issue by paszczaq** [syssi/nextbike#7]
Hi,
I've just updated my HASS instance to newest version 2023.11.0, but after update when I tried to check config it thrown an error when checking config
`Platform error sensor.nextbike - cannot import name 'distance' from 'homeassistant.util' (/usr/src/homeassistant/homeassistant/util/__init__.py)`

```
My config is pretty simple:
- platform: nextbike
  name: Veturilo
  city_id: 812
#  latitude: 52.229435
#  longitude: 21.094524
  radius: 500
```
While googling around i've came across this information - which might be related to this error?
https://developers.home-assistant.io/blog/2023/10/03/conversion-functions-cleanup/

**Comment by nepozs** [comment]
The same situation, different city
config example
```
  - platform: nextbike
    name: Factory NB
    city_id: 148
    latitude:  51.10702
    longitude: 16.94971
    radius: 30
```

**Comment by syssi** [comment]
I've prepared a fix. Please give it a try!
